# Monochrome dark theme - black & grey
foreground #d0d0d0
background #0e0e0e
cursor #a0a0a0
selection_background #444444
selection_foreground #e0e0e0

# black
color0  #0e0e0e
color8  #444444

# red (abu gelap)
color1  #666666
color9  #888888

# green (abu)
color2  #777777
color10 #999999

# yellow (abu terang)
color3  #888888
color11 #aaaaaa

# blue (abu sedang)
color4  #555555
color12 #777777

# magenta (abu)
color5  #666666
color13 #888888

# cyan (abu terang)
color6  #999999
color14 #bbbbbb

# white
color7  #c0c0c0
color15 #e0e0e0
