hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("GBM_BACKEND", "nvidia-drm")
-- Paksa app Electron (VSCode, Discord, dsb) lewat XWayland biar tidak flicker di NVIDIA + Hyprland
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "x11")
-- Matikan VRR/GSync di level driver (monitor sudah VRR off, ini cegah kedip)
hl.env("__GL_VRR_ALLOWED", "0")
hl.env("__GL_GSYNC_ALLOWED", "0")
